#' @include occumb.R
NULL

setMethod("show", "occumbFit",
  function(object) {
    print(object@fit)
  }
)

#' @export
# This code was created on April 2, 2026 by modifying the source code of the
# print.jagsUI() function in the jagsUI package licensed under the GPLv3.
print.nimbleSummary <- function(x, digits = 3, ...) {
  mc <- x$mcmc.info

  # Header
  cat("NIMBLE output for model '", x$modfile, "', generated by occumb.\n",
      sep = "")
  cat("Estimates based on", mc$n.chains, "chains of", mc$n.iter,
      "iterations,\n")
  cat("burn-in = ", mc$n.burnin, " iterations and thin rate = ",
      mc$n.thin, ",\n", sep = "")
  cat("yielding", mc$n.samples, "total samples from the joint posterior.\n")

  if (!x$parallel) {
    cat("MCMC ran for ", mc$elapsed.mins, " minutes at time ",
        paste(x$run.date), ".\n\n", sep = "")
  } else {
    cat("MCMC ran in parallel for ", mc$elapsed.mins, " minutes at time ",
        paste(x$run.date), ".\n\n", sep = "")
  }

  # Table
  if (mc$n.chains == 1) {
    col_idx <- c(1, 2, 3, 5, 7, 10, 11)
  } else {
    col_idx <- c(1, 2, 3, 5, 7, 10, 11, 8, 9)
  }
  tab <- x$summary[, col_idx, drop = FALSE]
  tab <- as.data.frame(round(tab, digits))
  tab[, "overlap0"] <- tab[, "overlap0"] == 1
  print(tab)

  #Print Rhat/n.eff information if necessary
  if (mc$n.chains > 1) {
    rhats <- unlist(tab[, "Rhat"])
    if (any(is.na(rhats))) {
      cat("\n**WARNING** Some Rhat values could not be calculated.\n")
    }
    if (!all(is.na(rhats)) && max(rhats, na.rm = TRUE) > 1.1) {
      cat("\n**WARNING** Rhat values indicate convergence failure.\n")
    } else if (!any(is.na(rhats))) {
      cat("\nSuccessful convergence based on Rhat values (all < 1.1).\n")
    }
    cat("Rhat is the potential scale reduction factor (at convergence, Rhat=1).\n")
    cat("For each parameter, n.eff is a crude measure of effective sample size.\n")
  }

  #Print overlap0/f statistic info
  cat("\noverlap0 checks if 0 falls in the parameter's 95% credible interval.\n")
  cat("f is the proportion of the posterior with the same sign as the mean;\n")
  cat("i.e., our confidence that the parameter is positive or negative.\n")

  invisible(x)
}

setMethod("show", "occumbGof",
  function(object) {
    statistics <- if (object@stats == "Freeman_Tukey") {
      "Freeman-Tukey"
    } else if (object@stats == "deviance") {
      "deviance"
    } else if (object@stats == "chi_squared") {
      "chi-squared"
    }
    cat(crayon::bold("Posterior predictive check for an occumbFit object:\n"))
    cat(" Statistics:", statistics, "\n")
    cat(" p-value:   ", round(object@p_value, 5), "\n")
    cat(" Discrepancy statistics for observed data:  ",
        round(mean(object@stats_obs), 2), "(mean),",
        round(stats::sd(object@stats_obs), 2), "(sd)",
        "\n")
    cat(" Discrepancy statistics for replicated data:",
        round(mean(object@stats_rep), 2), "(mean),",
        round(stats::sd(object@stats_rep), 2), "(sd)",
        "\n")
  }
)
